spring:
  security:
  oauth2:
  resourceserver:
  jwt:
  jwk-set-uri: http://localhost:8080/auth/realms/Townz/protocol/openid-connect/certs


server:
  port: 8081  # This is the default port anyway, but you can change it here

